/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 00:54:10 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.Appt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true)
public class Appt_ESTest extends Appt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Appt appt0 = new Appt(0, 23, 23, 0, (-1332), "43`ETqq6RkHR}6", "");
      appt0.setTitle("");
      appt0.setStartMonth((-2410));
      appt0.toString();
      appt0.getTitle();
      appt0.setStartDay(0);
      appt0.setStartYear(0);
      appt0.setStartDay(59);
      appt0.toString();
      appt0.setStartHour((-780));
      appt0.setTitle("");
      appt0.setTitle((String) null);
      appt0.setStartMonth((-780));
      appt0.toString();
      appt0.setDescription(" at ");
      appt0.getStartMinute();
      appt0.getStartHour();
      appt0.setStartMonth(23);
      appt0.setStartMinute((-2410));
      appt0.setStartMonth((-780));
      appt0.getStartDay();
      appt0.setStartHour(0);
      int int0 = appt0.getStartYear();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Appt appt0 = new Appt((-1), (-1), (-1), (-1), (-1), (String) null, (String) null);
      appt0.setStartHour(0);
      appt0.toString();
      appt0.getStartDay();
      appt0.setStartMinute((-1));
      appt0.setStartMinute(43);
      appt0.setStartHour(1);
      appt0.setDescription("");
      appt0.toString();
      appt0.setTitle((String) null);
      appt0.setStartHour(0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Appt appt0 = new Appt(2563, (-987), 2669, 11, (-987), "", "");
      appt0.setStartHour((-3196));
      appt0.setTitle("(OJqbo");
      appt0.getStartDay();
      appt0.toString();
      appt0.setStartDay(0);
      appt0.setDescription("");
      appt0.setStartYear((-987));
      appt0.toString();
      appt0.setStartMinute(0);
      appt0.setStartDay(11);
      appt0.getStartDay();
      appt0.setStartHour(0);
      appt0.toString();
      appt0.setStartHour(14);
      appt0.toString();
      appt0.getStartYear();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Appt appt0 = new Appt(2, 2, 37, 272, 247, (String) null, "m|=");
      appt0.setStartYear(37);
      appt0.setStartDay(2);
      appt0.getDescription();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Appt appt0 = new Appt(529, 529, 529, 529, 529, (String) null, "c~wW^IPN4/F[:qvno");
      appt0.getStartDay();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "ocBo(*'pVa9+&z)H&H)", "");
      appt0.setTitle("");
      appt0.setStartHour(488);
      appt0.setStartMinute(80);
      appt0.setStartYear(0);
      appt0.toString();
      appt0.setStartHour(0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Appt appt0 = new Appt(37, 37, 10, 379, 37, "\n", "%Y-%M-%D%z");
      appt0.getDescription();
      appt0.getDescription();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Appt appt0 = new Appt((-1469), (-1469), (-1469), (-1469), (-1469), "G%po;*O`N[", "G%po;*O`N[");
      appt0.getTitle();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Appt appt0 = new Appt(5, 60, 5, 60, 60, "", "<=7r{75]M{)");
      appt0.setStartMinute(5);
      appt0.getStartHour();
      appt0.getStartYear();
      appt0.getStartYear();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Appt appt0 = new Appt(0, 1970, 1, 31, 0, "IUgD_<", (String) null);
      appt0.getStartHour();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Appt appt0 = new Appt(2000, 0, (-2061), 0, (-2061), "org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl", "");
      appt0.setTitle("org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl");
      appt0.getDescription();
      appt0.getStartMinute();
      appt0.getStartMonth();
      appt0.setTitle("org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Appt appt0 = new Appt(60, 60, (-725), 60, 60, "Timezone", "Timezone");
      appt0.getValid();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Appt appt0 = new Appt(6, 15, 6, 15, 0, "jTm(~/}+bd79", ")Y_;6J`U");
      appt0.getStartMonth();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Appt appt0 = new Appt(Integer.MIN_VALUE, Integer.MIN_VALUE, 0, 0, 0, "Day", "Day");
      appt0.getStartMinute();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Appt appt0 = new Appt(828, 828, 828, (-1290), 23, "", "");
      appt0.getStartMonth();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Appt appt0 = new Appt((-299), (-299), (-2061), (-2061), (-2061), (String) null, "vOMKq`zGu-");
      appt0.setStartMinute(0);
      appt0.setDescription((String) null);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Appt appt0 = new Appt(0, (-1300), (-1300), 0, 0, "", "");
      appt0.toString();
      appt0.setStartMinute(59);
      appt0.setDescription("");
      appt0.toString();
      appt0.setStartHour((-1300));
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Appt appt0 = new Appt(23, 2315, 2315, (-1037), 0, "", "");
      appt0.toString();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 72, 0, ":$'I\"3>KP", "Hour");
      appt0.getStartDay();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, "", "");
      appt0.getTitle();
      appt0.toString();
      appt0.setDescription("\t12/12/12 at 12:12pm ,, \n");
      appt0.setDescription("B]l^}iJRCSiAf");
      appt0.setStartMonth(12);
      appt0.toString();
      appt0.toString();
      appt0.toString();
      appt0.getTitle();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 2229, ", ", ", ");
      appt0.getValid();
      appt0.setStartYear(1);
      appt0.setStartHour(12);
      appt0.setStartMinute(12);
      appt0.setStartMonth(0);
      appt0.setStartDay(12);
      appt0.toString();
      appt0.setDescription(", ");
      appt0.setStartDay((-129));
      appt0.setStartMonth(1);
      appt0.setStartMinute(1124);
      appt0.setTitle("--%M-%D%z");
      appt0.toString();
      appt0.toString();
      appt0.getTitle();
      appt0.getDescription();
      appt0.toString();
      appt0.getDescription();
      appt0.getValid();
      appt0.getTitle();
      appt0.getTitle();
      appt0.getDescription();
      appt0.getDescription();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 1075, (String) null, (String) null);
      appt0.setStartDay(11);
      appt0.toString();
      appt0.setStartMonth(1075);
      appt0.toString();
      appt0.toString();
      appt0.toString();
      appt0.setStartYear(11);
      appt0.setStartHour(1451);
      appt0.setTitle("`a");
      appt0.setStartHour(8);
      appt0.setStartMinute(8);
      appt0.toString();
      appt0.getDescription();
      appt0.toString();
      appt0.toString();
  }
}
